import type { Metadata } from 'next'
import {manrope} from "@/fonts/fonts";
import './globals.css'
import NextProvider from "@/provider/nextUIProvider";
import Providers from "@/provider/reactQueryProvider";
import {Header} from "@/components/layout/header";

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${manrope.className} antialiased`}>
        <Providers>
          <NextProvider>
            <Header/>
            <main className="w-full py-[4.5rem]">
              {children}
            </main>
          </NextProvider>
        </Providers>
      </body>
    </html>
  )
}
